### ISSUE TITLE
 ERROR  Failed to compile with 1 errors

### ISSUE THREAD

**Issue by yaokm320** [Acmenlei/Many-people-blog#4]
run serve出现如下的错误
```
This relative module was not found:

* ../components/Footer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/index.vue?vue&type=script&lang=js&
```

**Comment by Acmenlei** [comment]
看readme，需要自己创建一个Footer文件的。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yaokm320&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月29日(星期五) 下午3:47
收件人:&nbsp;&quot;Acmenlei/Many-people-blog&quot;<Many-people-blog@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Acmenlei/Many-people-blog]  ERROR  Failed to compile with 1 errors (#4)
